import "@/styles/globals.css";
import { Inter as FontSans, Raleway } from "next/font/google";
import { cn } from "@/lib/utils";

import { type Metadata } from "next";
import Providers from "@/components/layout/providers";
import { TRPCReactProvider } from "@/trpc/react";
import { getServerSession } from "next-auth";
import { Modal } from "@/components/modal";
import { Menu } from "@/components/menu";
import { SessionModal } from "@/components/sessionModal";
import { Toaster } from "@/components/ui/toaster";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--display-font",
});
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body
        className={cn(
          "font-sans min-h-screen bg-slate-900 antialiased",
          raleway.variable,
        )}
      >
        <Providers session={session}>
          <TRPCReactProvider>{children}</TRPCReactProvider>
          <Menu />
          <SessionModal />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
